name:                halatro
version:             0.1.0.0
# github:              "githubuser/halatro"
license:             BSD-3-Clause
author:              "Alex Dixon"
maintainer:          "alexander.dixon@warwick.ac.uk"
copyright:           "2025 Alex Dixon"

extra-source-files: []

description:         A simple implementation of the basic Balatro ruleset in Haskell, including a terminal user interface.

dependencies:
- base >= 4.7 && < 5
- containers
- text
- time
- random

language:    GHC2021

default-extensions:
  - RecordWildCards
  - LambdaCase

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  halatro-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halatro
    - brick
    - vty
    - vty-crossplatform

tests:
  halatro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halatro
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-reporter-muffled
    - random
    - ansi-terminal
    - QuickCheck